import { useEffect, useState, useRef } from 'react';
import { motion, useInView } from 'framer-motion';

function AnimatedCounter({ target, label, prefix = '', suffix = '' }: { target: number; label: string; prefix?: string; suffix?: string }) {
    const [count, setCount] = useState(0);
    const ref = useRef<HTMLDivElement>(null);
    const isInView = useInView(ref, { once: true });

    useEffect(() => {
        if (!isInView) return;
        const duration = 2000;
        const steps = 60;
        const increment = target / steps;
        let current = 0;
        const timer = setInterval(() => {
            current += increment;
            if (current >= target) {
                setCount(target);
                clearInterval(timer);
            } else {
                setCount(Math.floor(current));
            }
        }, duration / steps);
        return () => clearInterval(timer);
    }, [isInView, target]);

    return (
        <div ref={ref} className="text-center">
            <p className="text-2xl lg:text-3xl font-bold font-heading text-white">
                {prefix}{count.toLocaleString()}{suffix}
            </p>
            <p className="text-text-muted text-xs mt-1">{label}</p>
        </div>
    );
}

function MiniChart() {
    const data = [30, 45, 35, 60, 55, 70, 65, 80, 75, 90, 85, 95, 88, 100, 92];
    const max = Math.max(...data);
    const width = 300;
    const height = 120;
    const points = data.map((v, i) => ({
        x: (i / (data.length - 1)) * width,
        y: height - (v / max) * height,
    }));
    const pathD = points.map((p, i) => (i === 0 ? `M ${p.x} ${p.y}` : `L ${p.x} ${p.y}`)).join(' ');
    const areaD = pathD + ` L ${width} ${height} L 0 ${height} Z`;

    return (
        <svg viewBox={`0 0 ${width} ${height}`} className="w-full h-full" preserveAspectRatio="none">
            <defs>
                <linearGradient id="chartGrad" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="0%" stopColor="#6C3CE9" stopOpacity="0.4" />
                    <stop offset="100%" stopColor="#6C3CE9" stopOpacity="0" />
                </linearGradient>
                <linearGradient id="lineGrad" x1="0" y1="0" x2="1" y2="0">
                    <stop offset="0%" stopColor="#6C3CE9" />
                    <stop offset="100%" stopColor="#FF6B35" />
                </linearGradient>
            </defs>
            <path d={areaD} fill="url(#chartGrad)" />
            <path d={pathD} fill="none" stroke="url(#lineGrad)" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" />
            {points.map((p, i) =>
                i === points.length - 1 ? (
                    <circle key={i} cx={p.x} cy={p.y} r="4" fill="#FF6B35" stroke="#0F0F1A" strokeWidth="2" />
                ) : null
            )}
        </svg>
    );
}

function PosterCarousel() {
    const [active, setActive] = useState(0);
    const posters = [
        { title: 'Weekend Buffet Special', color: 'from-orange-500 to-red-500', icon: '🍛' },
        { title: 'Happy Hour Deal', color: 'from-purple-500 to-pink-500', icon: '🍸' },
        { title: 'Festival Night Event', color: 'from-green-400 to-teal-500', icon: '🎉' },
    ];

    useEffect(() => {
        const timer = setInterval(() => setActive((p) => (p + 1) % posters.length), 3000);
        return () => clearInterval(timer);
    }, []);

    return (
        <div className="space-y-3">
            <p className="text-text-muted text-xs font-medium uppercase tracking-wider">AI-Generated Creatives</p>
            {posters.map((poster, i) => (
                <motion.div
                    key={i}
                    animate={{ scale: i === active ? 1 : 0.95, opacity: i === active ? 1 : 0.5 }}
                    className={`rounded-xl bg-gradient-to-r ${poster.color} p-3 flex items-center gap-3 cursor-pointer`}
                    onClick={() => setActive(i)}
                >
                    <span className="text-2xl">{poster.icon}</span>
                    <div>
                        <p className="text-white text-sm font-semibold">{poster.title}</p>
                        <p className="text-white/70 text-xs">Auto-generated by AI</p>
                    </div>
                </motion.div>
            ))}
        </div>
    );
}

export default function DashboardPreview() {
    return (
        <motion.div
            initial={{ opacity: 0, y: 40 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, delay: 0.2 }}
            className="relative rounded-2xl bg-dark-surface border border-dark-border overflow-hidden glow-purple"
        >
            {/* Top bar */}
            <div className="flex items-center justify-between px-6 py-4 border-b border-dark-border">
                <div className="flex items-center gap-3">
                    <div className="flex gap-1.5">
                        <div className="w-3 h-3 rounded-full bg-red-500" />
                        <div className="w-3 h-3 rounded-full bg-yellow-500" />
                        <div className="w-3 h-3 rounded-full bg-green-500" />
                    </div>
                    <span className="text-text-muted text-xs font-mono">dashboard.bestorantai.com</span>
                </div>
                <div className="flex items-center gap-2">
                    <div className="w-2 h-2 rounded-full bg-accent animate-pulse" />
                    <span className="text-accent text-xs font-medium">Live</span>
                </div>
            </div>

            {/* Dashboard content */}
            <div className="p-6">
                {/* Stats row */}
                <div className="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
                    <div className="rounded-xl bg-dark-card border border-dark-border p-4">
                        <AnimatedCounter target={12} label="Ads Running" />
                    </div>
                    <div className="rounded-xl bg-dark-card border border-dark-border p-4">
                        <AnimatedCounter target={45200} label="Total Reach" suffix="" prefix="" />
                    </div>
                    <div className="rounded-xl bg-dark-card border border-dark-border p-4">
                        <AnimatedCounter target={34} label="ROI Multiple" prefix="" suffix="x" />
                    </div>
                    <div className="rounded-xl bg-dark-card border border-dark-border p-4">
                        <AnimatedCounter target={234} label="Budget Used" prefix="$" />
                    </div>
                </div>

                {/* Chart + Posters */}
                <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                    <div className="lg:col-span-2 rounded-xl bg-dark-card border border-dark-border p-5">
                        <div className="flex items-center justify-between mb-4">
                            <div>
                                <p className="text-white font-semibold text-sm">Campaign Performance</p>
                                <p className="text-text-muted text-xs">Last 30 days</p>
                            </div>
                            <div className="flex gap-2">
                                <span className="px-3 py-1 rounded-full bg-primary/20 text-primary-light text-xs font-medium">Reach</span>
                                <span className="px-3 py-1 rounded-full bg-secondary/20 text-secondary-light text-xs font-medium">Engagement</span>
                            </div>
                        </div>
                        <div className="h-32">
                            <MiniChart />
                        </div>
                    </div>
                    <div className="rounded-xl bg-dark-card border border-dark-border p-5">
                        <PosterCarousel />
                    </div>
                </div>
            </div>
        </motion.div>
    );
}
